cluster.name: "p2n"
server.name: elasticP2N
#network.host: localhost
#transport.host: 127.0.0.1
discovery.type: single-node
discovery.seed_hosts: ["127.0.0.1", "localhos"]

#transport.port: 9300
#http.port: 9200

