# Default Kibana configuration from kibana-docker.

server.name: kibanaP2N
server.host: "localhost"
elasticsearch.hosts: ["https://elasticsearch:9200"]
# elasticsearch.password is stored in `kibana.keystore`
elasticsearch.username: kibana
